version: 2.1

orbs:
  android: circleci/android@2.1.2

commands:
  save-build-cache: android/save-build-cache
  restore-build-cache: android/restore-build-cache

  save-gradle-cache:
    description: Save Gradle cache
    steps:
      - save_cache:
          key: gradle-orb-v1-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
          paths:
            - ~/.gradle

  restore-gradle-cache:
    description: Restore Gradle cache
    steps:
      - restore_cache:
          key: gradle-orb-v1-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}

  setup-environment:
    steps:
      - run:
          name: Setup Environment
          command: |
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "app/google-services.json" --decrypt "app/google-services.json.gpg"
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "upload-keystore.jks" --decrypt "upload-keystore.jks.gpg"
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "publish-key.json" --decrypt "publish-key.json.gpg"

  git-config:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6d:72:29:06:13:e6:c8:26:56:e2:b7:0f:1e:ce:4f:0e"
      - run:
          name: Set up Git config
          command: |
            git config user.email "bot@circleci.com"
            git config user.name "Circle CI"

  download-android-dependencies:
    steps:
      - run:
          name: Download Android Dependencies
          command: ./gradlew androidDependencies

  run-tests:
    steps:
      - run:
          name: Run Checks and Tests
          command: ./gradlew check --stacktrace

  build-debug:
    steps:
      - run:
          name: Build Debug APK
          command: ./gradlew assembleDebug --stacktrace

  build-release:
    steps:
      - run:
          name: Prepare Release Bundle
          command: ./gradlew bundleRelease --stacktrace

  publish-release:
    steps:
      - run:
          name: Upload to Google Play
          command: ./gradlew publishBundle --stacktrace

  increment-version:
    steps:
      - run:
          name: Increment Version
          command: |
            ./gradlew incrementPatch
            git commit -a -m "Set next dev version [ci skip]"
            git push

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large

    steps:
      - checkout
      - setup-environment
      - restore-gradle-cache
      - restore-build-cache
      - download-android-dependencies
      - save-gradle-cache
      - run-tests
      - build-debug
      - save-build-cache
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_test_results:
          path: app/build/test-results

  increment:
    executor:
      name: android/android-machine
      resource-class: large

    steps:
      - checkout
      - setup-environment
      - restore-gradle-cache
      - restore-build-cache
      - git-config
      - increment-version

  deploy:
    executor:
      name: android/android-machine
      resource-class: large

    steps:
      - checkout
      - setup-environment
      - restore-gradle-cache
      - restore-build-cache
      - build-release
      - publish-release

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - increment:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
