version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    environment:
      JVM_OPTS: -Xmx3g
        
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            echo $PLAYSTORE_CREDENTIALS
            gpg --passphrase "$GPG_KEY" --pinentry-mode loopback --output "upload-keystore.jks" --decrypt "upload-keystore.jks.gpg"
            gpg --passphrase "$GPG_KEY" --pinentry-mode loopback --output "publish-key.json" --decrypt "publish-key.json.gpg"
            cat $PLAYSTORE_CREDENTIALS
      - run:
          name: Run tests and checks
          command: ./gradlew check
      - store_artifacts:
          path: app/build/reports
          destination: reports
#      - store_test_results:
#          path: app/build/test-results
