version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "upload-keystore.jks" --decrypt "upload-keystore.jks.gpg"
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "publish-key.json" --decrypt "publish-key.json.gpg"
      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
            - ~/.gradle
      - run:
          command: ./gradlew build

  test:
    executor: android/android

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "upload-keystore.jks" --decrypt "upload-keystore.jks.gpg"
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "publish-key.json" --decrypt "publish-key.json.gpg"
      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
      - run:
          command: ./gradlew check

  deploy:
    executor: android/android

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "upload-keystore.jks" --decrypt "upload-keystore.jks.gpg"
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "publish-key.json" --decrypt "publish-key.json.gpg"
      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
      - run:
          command: ./gradlew publishBundle



