version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "upload-keystore.jks" --decrypt "upload-keystore.jks.gpg"
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "publish-key.json" --decrypt "publish-key.json.gpg"
      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
            - ~/.gradle
      - run:
          name: Build Artifacts
          command: ./gradlew build --stacktrace

  test:
    executor: android/android

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "upload-keystore.jks" --decrypt "upload-keystore.jks.gpg"
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "publish-key.json" --decrypt "publish-key.json.gpg"
      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
      - run:
          name: Run Tests and Checks
          command: ./gradlew check --stacktrace

  deploy:
    executor: android/android

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "upload-keystore.jks" --decrypt "upload-keystore.jks.gpg"
            gpg --passphrase $GPG_KEY --pinentry-mode loopback --output "publish-key.json" --decrypt "publish-key.json.gpg"
      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
      - run:
          name: Upload to Google Play
          command: ./gradlew bundleRelease publishBundle --stacktrace

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
