version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    environment:
      JVM_OPTS: -Xmx3g
        
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - run:
          name: Setup environment
          command: |
            gpg --passphrase "$GPG_KEY" --pinentry-mode loopback upload-keystore.jks.gpg
            gpg --passphrase "$GPG_KEY" --pinentry-mode loopback publish-key.json.gpg
      - run:
          name: Run tests and checks
          command: ./gradlew check
      - store_artifacts:
          path: app/build/reports
          destination: reports
#      - store_test_results:
#          path: app/build/test-results
