name: Android CI

on: [push]

jobs:
  build:
    name: Run checks and publish artifacts

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run checks and unit tests
      run: ./gradlew check --stacktrace
    - name: Assemble debug apk
      run: ./gradlew assembleDebug --stacktrace
    - id: getfilename
      name: Get apk file name
      run: echo "::set-output name=file::$(ls app/build/outputs/apk/debug/*.apk)"
    - name: Upload debug apk
      uses: actions/upload-artifact@v1
      with:
        name: launchiteasy
        path: ${{ steps.getfilename.outputs.file }}
